name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      MISE_ENV: production
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v4
      - run: npm ci
      - run: npx astro sync
      - run: npm run lint
      - run: npm run build
